GET http://172.24.125.247:28017/WORD-CLOUD/articles/ HTTP/1.1

###

GET http://localhost:27080 HTTP/1.1

###

POST http://127.0.0.1:27080/_connect/ HTTP/1.1
content-type: application/json

{
    "MONGO_URI": "172.27.107.98:27017",
    "MONGO_INITDB_ROOT_USERNAME": "root",
    "MONGO_INITDB_ROOT_PASSWORD": "sisko@7660$boo",
    "MONGO_INITDB_DATABASE": "admin",
    "MONGO_AUTH_MECHANISM": "SCRAM-SHA-256"
}

###

GET http://localhost:27080/list_databases/ HTTP/1.1

###

GET http://localhost:27080/_use/WORD-CLOUD/list_collections HTTP/1.1

###

GET http://localhost:27080/_use/WORD-CLOUD HTTP/1.1

###

GET http://localhost:27080/_use/WORD-CLOUD/articles/count_documents HTTP/1.1

###

GET http://localhost:27080/_use/WORD-CLOUD/articles/find HTTP/1.1


###

POST http://127.0.0.1:27080/_use/WORD-CLOUD/articles/find_one HTTP/1.1
content-type: application/json

{
    "filter": {"_id": "6011827480190cb556b7d406"}
}
